import { useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import AuthLayout from '../../../components/auth/AuthLayout/AuthLayout.jsx'
import PasswordField from '../../../components/auth/PasswordField/PasswordField.jsx'
import SocialLoginButtons from '../../../components/auth/SocialLoginButtons/SocialLoginButtons.jsx'
import useAuth from '../../../context/useAuth.jsx'
import { getAuthErrorDetails } from '../../../services/authService.js'
import { isApiConfigured } from '../../../config/api.js'
import './Register.css'

function validateField(field, value, form) {
  if (field === 'name') { if (!value.trim()) return 'Full name is required.'; if (value.trim().length < 2) return 'Name must contain at least 2 characters.' }
  if (field === 'email') { if (!value.trim()) return 'Email is required.'; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim())) return 'Please enter a valid email address.' }
  if (field === 'phone' && value.trim() && !/^(?:\+91[6-9]\d{9}|[6-9]\d{9})$/.test(value.trim())) return 'Please enter a valid mobile number.'
  if (field === 'role' && !value) return 'Please select an account type.'
  if (field === 'password') { if (!value) return 'Password is required.'; if (value.length < 8) return 'Password must contain at least 8 characters.' }
  if (field === 'confirmPassword') { if (!value) return 'Please confirm your password.'; if (value !== form.password) return 'Passwords do not match.' }
  return ''
}

function Register() {
  const { register } = useAuth(); const navigate = useNavigate()
  const [form, setForm] = useState({ name: '', email: '', phone: '', role: 'student', password: '', confirmPassword: '' }); const [errors, setErrors] = useState({}); const [status, setStatus] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false); const isConfigured = isApiConfigured
  const nameRef = useRef(null); const emailRef = useRef(null); const phoneRef = useRef(null); const passwordRef = useRef(null); const confirmPasswordRef = useRef(null)
  const update = (field, value) => { const nextForm = { ...form, [field]: value }; setForm(nextForm); const nextErrors = { ...errors, [field]: validateField(field, value, nextForm) || undefined }; if (field === 'password' && form.confirmPassword) nextErrors.confirmPassword = validateField('confirmPassword', form.confirmPassword, nextForm) || undefined; setErrors(nextErrors); setStatus('') }
  const validate = () => Object.fromEntries(Object.keys(form).map((field) => [field, validateField(field, form[field], form)]).filter(([, error]) => error))
  const submit = async (event) => { event.preventDefault(); const nextErrors = validate(); const refs = { name: nameRef, email: emailRef, phone: phoneRef, password: passwordRef, confirmPassword: confirmPasswordRef }; if (Object.keys(nextErrors).length) { setErrors(nextErrors); refs[Object.keys(nextErrors)[0]]?.current?.focus(); return } if (!isConfigured) { setStatus('Authentication is not connected yet.'); return } setIsSubmitting(true); setStatus(''); try { await register(form); navigate('/login', { replace: true, state: { registrationMessage: 'Account created successfully. Please sign in.' } }) } catch (error) { const details = error.authDetails ?? getAuthErrorDetails(error); const serverErrors = details.fieldErrors ?? {}; setErrors(serverErrors); refs[Object.keys(serverErrors)[0]]?.current?.focus(); setStatus(details.message) } finally { setIsSubmitting(false) } }
  const blur = (field) => setErrors((current) => ({ ...current, [field]: validateField(field, form[field], form) || undefined }))
  return <AuthLayout><div className="register-form-card"><span className="categories-eyebrow">JOIN CADTECH</span><h2>Create Your Account</h2><p className="register-description">Join CadTech Solution to explore courses, CAD models, and learning resources.</p>{status && <div className={`register-status ${status === 'Authentication is not connected yet.' ? 'register-notice' : 'register-status-error'}`} role="alert" aria-live="polite">{status}</div>}<form onSubmit={submit} noValidate><TextField id="register-name" label="Full Name" value={form.name} onChange={(value) => update('name', value)} onBlur={() => blur('name')} error={errors.name} inputRef={nameRef} placeholder="Enter your full name" autoComplete="name" /><TextField id="register-email" label="Email Address" value={form.email} onChange={(value) => update('email', value)} onBlur={() => blur('email')} error={errors.email} inputRef={emailRef} placeholder="Enter your email address" autoComplete="email" type="email" /><TextField id="register-phone" label="Mobile Number" value={form.phone} onChange={(value) => update('phone', value)} onBlur={() => blur('phone')} error={errors.phone} inputRef={phoneRef} placeholder="Enter your mobile number" autoComplete="tel" type="tel" /><fieldset className="role-field"><legend>Account Type <span aria-hidden="true">*</span></legend><div className="role-options"><label className={form.role === 'student' ? 'is-selected' : ''}><input type="radio" name="role" value="student" checked={form.role === 'student'} onChange={(event) => update('role', event.target.value)} onBlur={() => blur('role')} />Student</label><label className={form.role === 'instructor' ? 'is-selected' : ''}><input type="radio" name="role" value="instructor" checked={form.role === 'instructor'} onChange={(event) => update('role', event.target.value)} />Instructor</label></div>{errors.role && <span className="register-error" role="alert">{errors.role}</span>}<small>Instructor access is subject to backend confirmation.</small></fieldset><PasswordField id="register-password" label="Password" value={form.password} onChange={(event) => update('password', event.target.value)} onBlur={() => blur('password')} inputRef={passwordRef} error={errors.password} autoComplete="new-password" placeholder="Create a password" /><p className="password-guidance">Use at least 8 characters.</p><PasswordField id="register-confirm-password" label="Confirm Password" value={form.confirmPassword} onChange={(event) => update('confirmPassword', event.target.value)} onBlur={() => blur('confirmPassword')} inputRef={confirmPasswordRef} error={errors.confirmPassword} autoComplete="new-password" placeholder="Repeat your password" /><button className="button button-primary register-submit" type="submit" disabled={isSubmitting || !isConfigured}>{isSubmitting ? 'Creating Account...' : 'Create Account'}</button></form><p className="register-switch">Already have an account? <Link to="/login">Sign In</Link></p></div></AuthLayout>
}

function TextField({ id, label, value, onChange, onBlur, error, inputRef, placeholder, autoComplete, type = 'text' }) { return <div className="register-field"><label htmlFor={id}>{label} <span aria-hidden="true">*</span></label><input ref={inputRef} id={id} type={type} value={value} onChange={(event) => onChange(event.target.value)} onBlur={onBlur} placeholder={placeholder} autoComplete={autoComplete} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} />{error && <span className="register-error" id={`${id}-error`} role="alert">{error}</span>}</div> }
export default Register
