import { useEffect } from 'react'
import { Link, useLocation } from 'react-router-dom'
import './LegalPage.css'

const policies = {
  'privacy-policy': {
    title: 'Privacy Policy',
    source: 'https://cadtechsolution.com/privacy-policy',
    sections: [
      { title: 'Introduction', paragraphs: ['At Design With Ajay, we value your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, and safeguard your data when you visit our e-commerce platform at www.cadtechsolution.com or purchase our downloadable 2D/3D CAD drawings, blueprints, and schematics. By using our website, you agree to the practices outlined in this policy.'] },
      { title: '1. Information We Collect', paragraphs: ['We may collect the following personal information when you interact with our platform:'], bullets: ['Personal Details: Name, email address, shipping address, billing address, and phone number when you make a purchase or create an account.', 'Transactional Data: Payment details, order history, and purchased products (e.g., CAD files).', 'Device Information: IP address, browser type, operating system, and referring URLs to improve your browsing experience.', 'Cookies: We use cookies to enhance your experience, track preferences, and collect data on how you use our site. You can manage cookie settings in your browser.'] },
      { title: '2. How We Use Your Information', paragraphs: ['We use your information to:'], bullets: ['Process and fulfill your orders for CAD drawings and other digital products.', 'Communicate with you about your account, orders, and inquiries.', 'Improve our website, products, and services based on user feedback and analytics.', 'Send promotional emails and marketing communications (with your consent).', 'Prevent fraud and ensure the security of our platform.'] },
      { title: '3. Data Security', paragraphs: ['We implement industry-standard security measures to protect your personal information from unauthorized access, disclosure, or misuse. However, no method of transmission over the internet is completely secure, and we cannot guarantee absolute security. We encourage you to use strong passwords and keep your account details confidential.'] },
      { title: '4. Sharing of Information', paragraphs: ['We may share your information with:', 'Third-Party Service Providers: Trusted partners who assist us in operating our e-commerce platform, processing payments, fulfilling orders, and delivering products (e.g., payment gateways, shipping services).', 'Legal Authorities: When required by law or to protect our rights, property, or safety, we may disclose your information to comply with legal obligations. We do not sell or rent your personal information to third parties for marketing purposes.'] },
      { title: '5. Third-Party Links', paragraphs: ['Our website may contain links to third-party websites or services (e.g., social media platforms like YouTube, Instagram, or GrabCAD). We are not responsible for the privacy practices of these external sites. We recommend reviewing their privacy policies before sharing any personal information.'] },
      { title: '6. Your Rights', paragraphs: ['You have the following rights regarding your personal information:'], bullets: ['Access: Request access to the data we hold about you.', 'Correction: Update or correct any inaccurate information.', 'Deletion: Request the deletion of your personal data, subject to legal obligations.', 'Opt-Out: Unsubscribe from marketing emails at any time using the link in our emails.'], after: 'To exercise these rights, please contact us at arvind@cadtechsolution.com' },
      { title: '5. Contact Us', paragraphs: ['If you have any questions or need assistance with your purchase, we’re here to help. Please reach out to us:', 'Email: arvind@cadtechsolution.com', 'WhatsApp: +91-8839989046'] }
    ]
  },
  terms: {
    title: 'Terms & Conditions',
    source: 'https://cadtechsolution.com/terms-conditions',
    sections: [
      { title: 'Introduction', paragraphs: ['Please read these Terms and Conditions (“Terms”, “Terms and Conditions”) carefully before using cadtechsolution.com website (the “Service”) operated by CAD Tech Solution (“us”, “we”, or “our”).', 'Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who wish to access or use the Service.', 'By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you do not have permission to access the Service.', 'We use your Personal Information for providing and improving the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible at cadtechsolution.com'] },
      { title: 'Communications', paragraphs: ['By creating an Account on our service, you agree to subscribe to newsletters, marketing or promotional materials and other information we may send. However, you may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.'] },
      { title: 'Purchases', paragraphs: ['If you wish to purchase any product or service made available through the Service (“Purchase”), you may be asked to supply certain information relevant to your Purchase including, without limitation, your credit card number, the expiration date of your credit card, your billing address, and your shipping information.', 'You represent and warrant that: (i) you have the legal right to use any credit card(s) or other payment method(s) in connection with any Purchase; and that (ii) the information you supply to us is true, correct and complete.', 'The service may employ the use of third party services for the purpose of facilitating payment and the completion of Purchases. By submitting your information, you grant us the right to provide the information to these third parties subject to our Privacy Policy.', 'We reserve the right to refuse or cancel your order at any time for reasons including but not limited to: product or service availability, errors in the description or price of the product or service, error in your order or other reasons.', 'We reserve the right to refuse or cancel your order if fraud or an unauthorized or illegal transaction is suspected.'] },
      { title: 'Availability, Errors and Inaccuracies', paragraphs: ['We are constantly updating product and service offerings on the Service. We may experience delays in updating information on the Service and in our advertising on other web sites. The information found on the Service may contain errors or inaccuracies and may not be complete or current. Products or services may be mispriced, described inaccurately, or unavailable on the Service and we cannot guarantee the accuracy or completeness of any information found on the Service.', 'We therefore reserve the right to change or update information and to correct errors, inaccuracies, or omissions at any time without prior notice.'] },
      { title: 'Contests, Sweepstakes and Promotions', paragraphs: ['Any contests, sweepstakes or other promotions (collectively, “Promotions”) made available through the Service may be governed by rules that are separate from these Terms & Conditions. If you participate in any Promotions, please review the applicable rules as well as our Privacy Policy. If the rules for a Promotion conflict with these Terms and Conditions, the Promotion rules will apply.'] },
      { title: 'Subscriptions', paragraphs: ['Some parts of the Service are billed on a subscription basis (“Subscription(s)”). You will be billed in advance on a recurring and periodic basis (“Billing Cycle”). Billing cycles are set either on a monthly or annual basis, depending on the type of subscription plan you select when purchasing a Subscription.', 'At the end of each Billing Cycle, your Subscription will automatically renew under the exact same conditions unless you cancel it or CAD Tech Solution cancels it. You may cancel your Subscription renewal either through your online account management page or by contacting CAD Tech Solution customer support team.', 'A valid payment method, including credit card or PayPal, is required to process the payment for your Subscription. You shall provide CAD Tech Solution with accurate and complete billing information including full name, address, state, zip code, telephone number, and a valid payment method information. By submitting such payment information, you automatically authorize CAD Tech Solution to charge all Subscription fees incurred through your account to any such payment instruments.', 'Should automatic billing fail to occur for any reason, CAD Tech Solution will issue an electronic invoice indicating that you must proceed manually, within a certain deadline date, with the full payment corresponding to the billing period as indicated on the invoice.'] },
      { title: 'Fee Changes', paragraphs: ['CAD Tech Solution in its sole discretion and at any time, may modify the Subscription fees for the Subscriptions. Any Subscription fee change will become effective at the end of the then-current Billing Cycle.', 'CAD Tech Solution will provide you with a reasonable prior notice of any change in Subscription fees to give you an opportunity to terminate your Subscription before such change becomes effective.', 'Your continued use of the Service after the Subscription fee change comes into effect constitutes your agreement to pay the modified Subscription fee amount.'] },
      { title: 'Refunds', paragraphs: ['Except when required by law, paid Subscription fees are non-refundable.'] },
      { title: 'Content', paragraphs: ['Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material (“Content”). You are responsible for the Content that you post on or through the Service, including its legality, reliability, and appropriateness.', 'By posting Content on or through the Service, You represent and warrant that: (i) the Content is yours (you own it) and/or you have the right to use it and the right to grant us the rights and license as provided in these Terms, and (ii) that the posting of your Content on or through the Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person or entity. We reserve the right to terminate the account of anyone found to be infringing on a copyright. You retain any and all of your rights to any Content you submit, post or display on or through the Service and you are responsible for protecting those rights. We take no responsibility and assume no liability for Content you or any third party posts on or through the Service. However, by posting Content using the Service you grant us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through the Service. You agree that this license includes the right for us to make your Content available to other users of the Service, who may also use your Content subject to these Terms.', 'CAD Tech Solution has the right but not the obligation to monitor and edit all Content provided by users.', 'In addition, Content found on or through this Service is the property of CAD Tech Solution or used with permission. You may not distribute, modify, transmit, reuse, download, repost, copy, or use said Content, whether in whole or in part, for commercial purposes or for personal gain, without express advance written permission from us.'] },
      { title: 'Accounts', paragraphs: ['When you create an account with us, you guarantee that you are above the age of 18, and that the information you provide us is accurate, complete, and current at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your account on the Service.', 'You are responsible for maintaining the confidentiality of your account and password, including but not limited to the restriction of access to your computer and/or account. You agree to accept responsibility for any and all activities or actions that occur under your account and/or password, whether your password is with our Service or a third-party service. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.', 'You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than you, without appropriate authorization. You may not use as a username any name that is offensive, vulgar or obscene.', 'We reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in our sole discretion.'] },
      { title: 'Intellectual Property', paragraphs: ['The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of CAD Tech Solution and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of CAD Tech Solution'] },
      { title: 'Acceptable Use Policy', paragraphs: ['We do not allow image uploads, video linking or files linking or the use of CAD Tech Solution pages, resources or assets on websites that are of the following nature: Pornographic, racist, hate, defamatory/libelous, extreme violence or the promotion of violence/terrorism, self harm, narcotics, controlled substances or other products/services that present a risk to consumer safety, deceptive, misleading, fraudulent or otherwise illegal activities.', 'PLEASE NOTE THAT YOUR ACCOUNT WILL BE TERMINATED IMMEDIATELY AND WITHOUT NEGOTIATION IF YOU BREAK THIS AUP AGREEMENT'] },
      { title: 'Links To Other Web Sites', paragraphs: ['Our Service may contain links to third party web sites or services that are not owned or controlled by CAD Tech Solution.', 'CAD Tech Solution has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites.', 'You acknowledge and agree that CAD Tech Solution shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such third party web sites or services.', 'We strongly advise you to read the terms and conditions and privacy policies of any third party web sites or services that you visit.'] },
      { title: 'Termination', paragraphs: ['We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms.', 'If you wish to terminate your account, you may simply discontinue using the Service.', 'All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.'] },
      { title: 'Indemnification', paragraphs: ['You agree to defend, indemnify and hold harmless CAD Tech Solution and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password; b) a breach of these Terms, or c) Content posted on the Service.'] },
      { title: 'Limitation Of Liability', paragraphs: ['In no event shall CAD Tech Solution, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.'] },
      { title: 'Disclaimer', id: 'disclaimer', paragraphs: ['Your use of the Service is at your sole risk. The Service is provided on an “AS IS” and “AS AVAILABLE” basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance.', 'CAD Tech Solution its subsidiaries, affiliates, and its licensors do not warrant that a) the Service will function uninterrupted, secure or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.'] },
      { title: 'Exclusions', paragraphs: ['Some jurisdictions do not allow the exclusion of certain warranties or the exclusion or limitation of liability for consequential or incidental damages, so the limitations above may not apply to you.'] },
      { title: 'Governing Law', paragraphs: ['These Terms shall be governed and construed in accordance with the laws of Delaware, United States, without regard to its conflict of law provisions.', 'Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have had between us regarding the Service.'] },
      { title: 'Changes', paragraphs: ['We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will provide at least 30 days notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.', 'By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Service.'] },
      { title: 'Contact Us', paragraphs: ['If you have any questions about these Terms, please contact us.'] }
    ]
  },
  'digital-item-policy': {
    title: 'Digital Item Policy',
    source: 'https://cadtechsolution.com/digital-item-policy',
    sections: [
      { title: 'Introduction', paragraphs: ['This Digital Item Policy outlines the terms for purchasing, downloading, and using digital products from Design With Ajay at https://cadtechsolution.com/. Our platform offers downloadable 2D/3D CAD drawings, blueprints, and schematics for engineering, design, and DIY projects. By purchasing or downloading our digital items, you agree to adhere to these terms.'] },
      { title: '1. Purchase and Delivery', paragraphs: ['Availability: Digital items are available for purchase and download immediately after payment confirmation.', 'Delivery: Upon successful payment, you will receive a download link via email and through your account on our platform. Download links are valid for a limited time; we recommend downloading your files promptly.', 'Compatibility: You are responsible for ensuring your device and software (e.g., SolidWorks, AutoCAD) are compatible with the file formats provided (e.g., DWG, STEP, STL).'] },
      { title: '2. Usage Rights', paragraphs: ['License: When you purchase a digital item, you are granted a non-exclusive, non-transferable license to use the CAD file for personal or commercial projects, as specified in the product description.', 'Restrictions: You may not resell, redistribute, modify, or share the digital item in any way that violates the terms of this license. Unauthorized use may result in legal action.'] },
      { title: '3. Refunds', paragraphs: ['Policy: Due to the digital nature of our products, all sales are final. Refunds are not offered unless the item is defective (e.g., corrupted file) or does not match the product description.', 'Defective Items: If you encounter issues with a digital item, please contact us within 7 days of purchase for assistance. We will provide a replacement file or issue a refund if the issue cannot be resolved.', 'Contact: Email us at arvind@cadtechsolution.com with your order details to request a refund or support.'] },
      { title: '4. Intellectual Property', paragraphs: ['Ownership: All digital items, including CAD designs, remain the intellectual property of Design With Ajay or its licensors.', 'Copyright: You may not claim ownership or copyright over any digital item purchased from us. Unauthorized use, reproduction, or distribution of our designs is strictly prohibited and may result in legal action.'] },
      { title: '5. Security and Access', paragraphs: ['Our Responsibility: We take measures to ensure the security of your digital downloads and protect them from unauthorized access.', 'Your Responsibility: You are responsible for maintaining the security of your account credentials and ensuring that only authorized individuals have access to the downloaded files.'] },
      { title: '6. Technical Support', paragraphs: ['Support: We provide limited technical support for digital items, including assistance with download issues or file compatibility.', 'Contact: For technical support, please reach out to us at arvind@cadtechsolution.com or via WhatsApp at +91 948542846. We aim to respond within 24 hours during operating hours.'] },
      { title: '7. Contact Information', paragraphs: ['If you have any questions or concerns about this Digital Item Policy, please contact us:', 'Email: arvind@cadtechsolution.com', 'WhatsApp: +91 8839989046'] }
    ]
  },
  'refund-policy': {
    title: 'Refund Policy',
    source: 'https://cadtechsolution.com/refund-policy',
    sections: [
      { title: 'Introduction', paragraphs: ['At Design With Ajay, we strive to ensure you’re completely satisfied with your purchase of our downloadable 2D/3D CAD drawings, blueprints, and schematics. This Refund Policy outlines the conditions under which refunds may be issued for digital products purchased through our e-commerce platform at www.cadtechsolution.com. Please read this policy carefully before making a purchase.'] },
      { title: '1. General Policy', paragraphs: ['Due to the digital nature of our products, all sales are final once the order is confirmed and the download link is sent. We do not offer refunds or exchanges for digital downloads unless the product is defective or does not match the product description.'] },
      { title: '2. Eligible Refund Scenarios', paragraphs: ['Refunds may be issued under the following circumstances:', 'Defective Files: If the CAD file is corrupted, incomplete, or cannot be opened in the specified format (e.g., DWG, STEP, STL).', 'Incorrect Product: If the downloaded file does not match the product description or is not the item you purchased.', 'To be eligible for a refund, you must contact us within 7 days of purchase with proof of the issue (e.g., screenshots or error messages).'] },
      { title: '3. Refund Process', paragraphs: ['Request: To request a refund, email us at arvind@cadtechsolution.com with your order number, a description of the issue, and any supporting evidence (e.g., screenshots).', 'Review: We will review your request within 48 hours and may provide a replacement file if the issue can be resolved.', 'Refund Issuance: If a replacement is not possible, a full refund will be issued to your original payment method within 5 business days of approval.'] },
      { title: '4. Non-Refundable Scenarios', paragraphs: ['Refunds will not be issued in the following cases:'], bullets: ['You change your mind after downloading the file.', 'Your device or software is incompatible with the file format (please check compatibility before purchasing).', 'You fail to download the file within the provided time limit (download links are valid for a limited period).', 'The file was used or shared in violation of our usage license.'] },
      { title: '5. Contact Us', paragraphs: ['If you have any questions or need assistance with your purchase, we’re here to help. Please reach out to us:', 'Email: arvind@cadtechsolution.com', 'WhatsApp: +91-8839989046'] }
    ]
  }
}

const legalLinks = [
  ['Privacy Policy', '/privacy-policy'],
  ['Terms & Conditions', '/terms'],
  ['Digital Item Policy', '/digital-item-policy'],
  ['Refund Policy', '/refund-policy']
]

function LegalPage() {
  const { pathname } = useLocation()
  const slug = pathname.replace(/^\//, '')
  const policy = slug ? policies[slug] : null

  useEffect(() => {
    if (window.location.hash === '#disclaimer') {
      requestAnimationFrame(() => document.getElementById('disclaimer')?.scrollIntoView())
    }
  }, [slug])

  if (!slug || slug === 'legal') return <LegalInformation />
  if (!policy) return null

  return (
    <main className="legal-page site-container">
      <header className="legal-page-header"><p className="legal-eyebrow">CAD TECH SOLUTION · LEGAL</p><h1>{policy.title}</h1><p>Published policy text from the official CAD Tech Solution website.</p></header>
      <article className="legal-document">
        {policy.sections.map((section) => <section className="legal-section" key={section.title} id={section.id}>
          <h2>{section.title}</h2>
          {section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
          {section.bullets && <ul>{section.bullets.map((item) => <li key={item}>{item}</li>)}</ul>}
          {section.after && <p>{section.after}</p>}
        </section>)}
        <footer className="legal-source"><span>Official source</span><a href={policy.source} target="_blank" rel="noreferrer">View the published {policy.title.toLowerCase()} <span aria-hidden="true">↗</span></a></footer>
      </article>
      <nav className="legal-related" aria-label="Other legal policies">{legalLinks.filter(([, path]) => path !== `/${slug}`).map(([label, path]) => <Link to={path} key={path}>{label}</Link>)}</nav>
    </main>
  )
}

function LegalInformation() {
  return (
    <main className="legal-page site-container">
      <header className="legal-page-header"><p className="legal-eyebrow">CAD TECH SOLUTION</p><h1>Legal Information</h1><p>Published legal policies and business contact information from the official website.</p></header>
      <section className="legal-document legal-business-info">
        <h2>Business information published on the official website</h2>
        <dl><div><dt>Business name</dt><dd>CAD Tech Solution</dd></div><div><dt>Founder</dt><dd>Arvind Nagpure</dd></div><div><dt>Established</dt><dd>2020</dd></div><div><dt>Email</dt><dd><a href="mailto:arvind@cadtechsolution.com">arvind@cadtechsolution.com</a></dd></div><div><dt>Phone / WhatsApp</dt><dd><a href="tel:+918839989046">+91-8839989046</a></dd></div><div><dt>Hours</dt><dd>Monday-Saturday, 8AM-8PM</dd></div></dl>
        <p className="legal-source-note">The official website does not publish a business address or registration number in the information reviewed. Policy pages also use the name “Design With Ajay” and contain differing WhatsApp numbers; the wording and details on each policy page are preserved as published.</p>
        <p><a href="https://www.cadtechsolution.com" target="_blank" rel="noreferrer">Source: official CAD Tech Solution website <span aria-hidden="true">↗</span></a></p>
      </section>
      <nav className="legal-index" aria-label="Legal policies">{legalLinks.map(([label, path]) => <Link to={path} key={path}>{label}<span aria-hidden="true">→</span></Link>)}<Link to="/terms#disclaimer">Disclaimer section<span aria-hidden="true">→</span></Link></nav>
    </main>
  )
}

export default LegalPage