const courses = [
  { slug: 'autocad-essential-training', title: 'AutoCAD Essential Training', shortDescription: 'Learn AutoCAD fundamentals, 2D drafting, technical drawing, and essential design tools.', software: 'AutoCAD', category: '2D Drafting', level: 'Beginner', duration: '6 hours', lessons: 12, image: '/images/courses/autocad-essential-training.webp', priceInPaise: null, currency: 'INR', enrollmentOpen: false, status: 'published' },
  { slug: 'solidworks-part-modeling', title: 'SolidWorks Part Modeling', shortDescription: 'Create professional mechanical parts, assemblies, and 3D models using SolidWorks.', software: 'SolidWorks', category: 'Mechanical Design', level: 'Intermediate', duration: '8 hours', lessons: 18, image: '/images/courses/solidworks-part-modeling.webp', priceInPaise: null, currency: 'INR', enrollmentOpen: false, status: 'published' },
  { slug: 'revit-architecture-mastery', title: 'Revit Architecture Mastery', shortDescription: 'Design architectural structures and building information models with Autodesk Revit.', software: 'Revit', category: 'Architecture', level: 'Advanced', duration: '10 hours', lessons: 20, image: '/images/courses/revit-architecture-mastery.webp', priceInPaise: null, currency: 'INR', enrollmentOpen: false, status: 'published' },
  { slug: 'autocad-electrical-fundamentals', title: 'AutoCAD Electrical Fundamentals', shortDescription: 'Build a foundation in electrical drawings, wiring layouts, and panel documentation.', software: 'AutoCAD Electrical', category: 'Electrical Design', level: 'Beginner', duration: '5 hours', lessons: 10, image: '/images/courses/autocad-electrical-fundamentals.webp', priceInPaise: null, currency: 'INR', enrollmentOpen: false, status: 'published' },
  { slug: 'solidworks-assembly-design', title: 'SolidWorks Assembly Design', shortDescription: 'Develop assemblies, component relationships, and mechanical movement in SolidWorks.', software: 'SolidWorks', category: 'Mechanical Design', level: 'Intermediate', duration: '7 hours', lessons: 15, image: '/images/courses/solidworks-assembly-design.webp', priceInPaise: null, currency: 'INR', enrollmentOpen: false, status: 'published' },
  { slug: 'product-design-fundamentals', title: 'Product Design Fundamentals', shortDescription: 'Learn design thinking, product sketching, 3D modeling, and prototype preparation.', software: 'General CAD', category: 'Product Design', level: 'Beginner', duration: '4 hours', lessons: 9, image: '/images/courses/product-design-fundamentals.webp', priceInPaise: null, currency: 'INR', enrollmentOpen: false, status: 'published' },
  { slug: 'revit-interior-layouts', title: 'Revit Interior Layouts', shortDescription: 'Plan interior spaces, rooms, furniture placement, and presentation drawings in Revit.', software: 'Revit', category: 'Architecture', level: 'Intermediate', duration: '6 hours', lessons: 13, image: '/images/courses/revit-interior-layouts.webp', priceInPaise: null, currency: 'INR', enrollmentOpen: false, status: 'published' },
  { slug: 'mechanical-drawing-essentials', title: 'Mechanical Drawing Essentials', shortDescription: 'Practice engineering drawings, annotations, orthographic views, and component documentation.', software: 'AutoCAD', category: 'Mechanical Design', level: 'Beginner', duration: '5 hours', lessons: 11, image: '/images/courses/mechanical-drawing-essentials.webp', priceInPaise: null, currency: 'INR', enrollmentOpen: false, status: 'published' },
]

export const getCourseBySlug = (slug) => courses.find((course) => course.slug === slug) || null

export default courses